# frozen_string_literal: true

default_platform(:ios)

OS = '18.2'
IPHONE_DEVICE = "iPhone SE (3rd generation) (#{OS})".freeze

PROJECT_ROOT_FOLDER = File.join(File.dirname(File.expand_path(__dir__)), 'Demo')
BUILD_FOLDER = File.join(__dir__, '.build')
LOGS_FOLDER = File.join(BUILD_FOLDER, 'logs')
DERIVED_DATA_FOLDER = File.join(BUILD_FOLDER, 'derived-data')
ARTIFACTS_FOLDER = File.join(BUILD_FOLDER, 'artifacts')
XCODEPROJ_PATH = File.join(PROJECT_ROOT_FOLDER, 'Gravatar-Demo.xcodeproj')
DEMO_APPS_SOURCES_FOLDER = File.join(PROJECT_ROOT_FOLDER, 'Demo')
XCCONFIG_PROTOTYPE_BUILD = File.join(DEMO_APPS_SOURCES_FOLDER, 'Gravatar-Demo', 'Gravatar-Demo.Release.xcconfig')
COMMON_XCARGS = ['-skipPackagePluginValidation'].freeze # Allow SwiftPM plugins (e.g. swiftlint) called from Xcode to be used on CI without prior manual approval

GITHUB_REPO = 'Automattic/Gravatar-SDK-iOS'
GITHUB_URL = "https://github.com/#{GITHUB_REPO}".freeze

FIREBASE_APP_ID = '1:124902176124:ios:0fc3cbe4d84305531620f9'
FIREBASE_TESTERS_GROUP = 'gravatarsdk-ios---prototype-builds'

require_relative 'lib/env_manager'
require_relative 'lib/code_signing_helpers'

########################################################################
# Imports domain-specific lanes
########################################################################

import 'lanes/localization.rb'

########################################################################

before_all do
  EnvManager.set_up(env_file_name: 'gravatar-sdk-ios')

  # Various actions run 'xcodebuild -showBuildSettings ...' which can at times fail, possibly due to networking and SPM resolution.
  #
  # Bumping the interval Fastlane waits for xcodebuild to provide output before retrying seems to be an effective workaround.
  #
  # See also https://github.com/fastlane/fastlane/issues/20919
  ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '120'

  # Fixes known Keychain access issue in CI. No-op on local machines.
  # See https://docs.fastlane.tools/actions/setup_ci/
  setup_ci
end

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      package_path: '.',
      scheme: 'Gravatar-Package',
      xcargs: COMMON_XCARGS,
      device: IPHONE_DEVICE,
      prelaunch_simulator: true,
      clean: true,
      buildlog_path: LOGS_FOLDER,
      derived_data_path: DERIVED_DATA_FOLDER
    )
  end

  desc 'Builds the Gravatar-Demo project with a specific scheme'
  lane :build_demo do |scheme: 'Gravatar-Demo'|
    # We only need to build for testing to ensure that the project builds.
    # There are no tests in the the Demo apps
    run_tests(
      project: XCODEPROJ_PATH,
      scheme: scheme,
      configuration: 'Debug',
      xcargs: COMMON_XCARGS,
      device: IPHONE_DEVICE,
      clean: true,
      build_for_testing: true,
      buildlog_path: LOGS_FOLDER,
      derived_data_path: DERIVED_DATA_FOLDER,
      disable_package_automatic_updates: true
    )
  end

  desc 'Builds the demo app from the given scheme for distribution'
  lane :build_demo_for_distribution do |scheme:, build_number:|
    UI.user_error! 'Please pass a build number by calling the lane with build_number:VALUE' if build_number.nil? || build_number.empty?

    build_app(
      project: XCODEPROJ_PATH,
      scheme: scheme,
      configuration: 'Release',
      export_method: 'enterprise',
      output_directory: ARTIFACTS_FOLDER,
      xcargs: [
        "CURRENT_PROJECT_VERSION=#{build_number}",
        *COMMON_XCARGS
      ]
    )
  end

  desc 'Upload the demo app to Firebase App Distribution'
  lane :upload_demo_to_firebase do |build_number:|
    EnvManager.require_env_vars!('FIREBASE_APP_DISTRIBUTION_ACCOUNT_KEY')

    release_notes = <<~NOTES
      Pull Request: ##{ENV.fetch('BUILDKITE_PULL_REQUEST', 'N/A')}
      Branch: `#{ENV.fetch('BUILDKITE_BRANCH', 'N/A')}`
      Commit: #{ENV.fetch('BUILDKITE_COMMIT', 'N/A')[0...7]}
    NOTES

    firebase_app_distribution(
      app: FIREBASE_APP_ID,
      service_credentials_json_data: EnvManager.get_required_env!('FIREBASE_APP_DISTRIBUTION_ACCOUNT_KEY'),
      release_notes: release_notes,
      groups: FIREBASE_TESTERS_GROUP
    )

    next if ENV.fetch('BUILDKITE_PULL_REQUEST', 'false') == 'false'

    # Post PR Comment
    comment_body = prototype_build_details_comment(
      app_display_name: 'Gravatar Prototype Build',
      fold: true
    )
    comment_on_pr(
      project: GITHUB_REPO,
      pr_number: Integer(ENV.fetch('BUILDKITE_PULL_REQUEST', nil)),
      reuse_identifier: 'prototype-build-link-gravtar-demo',
      body: comment_body
    )
  end

  desc 'Fetches the code signing certificate and provisioning profile for the prototype builds'
  lane :configure_code_signing do |readonly: true|
    # Run one call only with multiple bundle ids to authenticate only once.
    #
    # While building this for the first time, running dedicated calls for each bundle identifiers with readonly = false resulted in the first working and the second failing with the same error as https://github.com/fastlane/fastlane/issues/21132
    #
    # The logs for the second call had:
    #
    # Available session is not valid anymore. Continuing with normal login.
    #
    # Which suggest the authenticated session from the first call was not carried over to the second.
    configure_code_signing(
      bundle_ids: [bundle_id_prototype_build!],
      readonly: readonly
    )
  end
end

def configure_code_signing(bundle_ids:, readonly:)
  EnvManager.require_env_vars!(*CODE_SIGNING_ENV_VARS)
  EnvManager.require_env_vars!('MATCH_PASSWORD') if is_ci

  prompt_user_for_app_store_connect_credentials unless readonly

  sync_code_signing(
    type: 'enterprise',
    team_id: team_id_prototype_build!,
    app_identifier: bundle_ids,
    readonly: readonly,
    **CODE_SIGNING_STORAGE_OPTIONS
  )
end

def team_id_prototype_build!
  read_from_xcconfig!(key: 'DEVELOPMENT_TEAM', xcconfig: File.join(DEMO_APPS_SOURCES_FOLDER, 'Enterprise.xcconfig'))
end

def bundle_id_prototype_build!
  read_from_xcconfig!(key: 'PRODUCT_BUNDLE_IDENTIFIER', xcconfig: XCCONFIG_PROTOTYPE_BUILD)
end

def read_from_xcconfig!(key:, xcconfig:)
  configs = Xcodeproj::Config.new(xcconfig).attributes

  UI.user_error!("Could not find value for #{key} in xcconfig!") unless configs.key?(key)

  configs[key]
end
